import os.path
import argparse
import subprocess


def make_dummy(header, wd):
    with open(os.path.join(wd, "dummy.c"), "w") as f:
        f.write("/* Autogenerated! */\n")
        f.write("#include <{}>\n".format(header))


def run_make(struct, output, wd):
    subprocess.check_call(["make",
                           "TARGET_STRUCT={}".format(struct),
                           "LAYOUT_OUTPUT={}".format(os.path.abspath(output))],
                          cwd=wd)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Dump the layout of a kernel struct")
    parser.add_argument("struct", help="name of the struct to dump (e.g 'sk_buff')")
    parser.add_argument("header", help="header file to include for this struct (e.g 'linux/skbuff.h')")
    parser.add_argument("output", help="output file")

    args = parser.parse_args()

    wd = os.path.abspath(os.path.dirname(__file__))

    make_dummy(args.header, wd)
    run_make(args.struct, args.output, wd)
